# Generated by Django 6.0.4 on 2026-05-07 23:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bodega',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CabeceraPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_id', models.UUIDField(help_text='UUID del cliente en MS-Clientes. Sin FK directa: comunicación vía HTTP.')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('destinatario_nombre', models.CharField(max_length=200)),
                ('destinatario_rut', models.CharField(help_text='Formato: 12.345.678-9', max_length=12)),
                ('destinatario_telefono', models.CharField(max_length=20)),
                ('destinatario_correo', models.EmailField(max_length=254)),
                ('destinatario_direccion', models.TextField()),
                ('destinatario_codigo_postal', models.CharField(help_text='Código postal de la dirección del destinatario.', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cabecera_pedido',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=300)),
                ('sku', models.CharField(help_text='Referencia lógica al MS-Inventario. Sin FK directa.', max_length=100)),
                ('tipo_carga', models.CharField(choices=[('Fragil', 'Frágil'), ('Duro', 'Duro/Resistente'), ('Peligrosa', 'Carga Peligrosa'), ('Perecedera', 'Carga Perecedera'), ('General', 'Carga General'), ('Voluminosa', 'Carga Voluminosa')], default='General', max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hora_retiro', models.DateTimeField(help_text='Fecha y hora en que el producto se retira de bodega.')),
                ('hora_despacho', models.DateTimeField(help_text='Fecha y hora programada de salida hacia la dirección de entrega.')),
                ('direccion_entrega', models.TextField(help_text='Dirección de entrega específica para este ítem del pedido.')),
                ('codigo_postal_entrega', models.CharField(help_text='Código postal de la dirección de entrega de este ítem.', max_length=10)),
                ('bodega_origen', models.ForeignKey(help_text='PROTECT sirve para que no se pueda eliminar una bodega con despachos activos.', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='pedidos.bodega')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.cabecerapedido')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.CreateModel(
            name='GuiaDespacho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_guia', models.CharField(help_text='Número correlativo legible Ej: GD-2025-00042', max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('firma_responsable_despacho', models.TextField(blank=True, help_text='Nombre o firma digital del responsable de autorizar el despacho.', null=True)),
                ('fecha_firma_despacho', models.DateTimeField(blank=True, null=True)),
                ('firma_receptor', models.TextField(blank=True, help_text='Nombre o firma digital del receptor en la dirección de entrega.', null=True)),
                ('fecha_firma_receptor', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guia_despacho', to='pedidos.cabecerapedido')),
            ],
            options={
                'db_table': 'guia_despacho',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
